CMMS.Web/Controllers/PartTypeController.cs
using ClassLibrary.Models;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Helpers;
using static ClassLibrary.Common.Enums;

namespace WebApplication.Controllers
{
    [CustomAuthorization]
    public class PartTypeController : BaseController
    {
        private static Logger _logger;

        public PartTypeController()
        {
            _logger = LogManager.GetCurrentClassLogger();
        }

        public ActionResult Index()
        {
            string actionName = "Index";
            List<tbl_PartType> response = new List<tbl_PartType>();
            try
            {
                _logger.Log(LogLevel.Trace, actionName + " :: started.");
                using (WebAppDbContext db = new WebAppDbContext())
                {
                    response = db.tbl_PartType.ToList();
                }
                _logger.Log(LogLevel.Trace, actionName + " :: ended.");
            }
            catch(Exception ex)
            {
                _logger.Log(LogLevel.Error, actionName + " EXCEPTION :: " + ex.ToString() + " INNER EXCEPTION :: " + ex.InnerException?.ToString());
            }
            return View(response);
        }
 
        public ActionResult Details(string id)
        {
            string actionName = "Details";
            tbl_PartType response = new tbl_PartType();
            try
            {
                _logger.Log(LogLevel.Trace, actionName + " :: started.");

                if (String.IsNullOrWhiteSpace(id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                else
                {
                    using (WebAppDbContext db = new WebAppDbContext())
                    {
                        response = db.tbl_PartType.FirstOrDefault(x => x.PartTypeID == id);
                    }
                }
                _logger.Log(LogLevel.Trace, actionName + " :: ended.");
            }
            catch(Exception ex)
            {
                _logger.Log(LogLevel.Error, actionName + " EXCEPTION :: " + ex.ToString() + " INNER EXCEPTION :: " + ex.InnerException?.ToString());
            }

            return PartialView("_Details", response);
        }

        // GET: AreaType/Create
        //public ActionResult Create()
        //{
        //    return PartialView("_Create");
        //}

        //// POST: AreaType/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(tbl_PartType tbl_PartType)
        //{
        //    string actionName = "Create";
        //    try
        //    {
        //        _logger.Log(LogLevel.Trace, actionName + " :: started.");
                 
        //        if(ModelState.IsValid)
        //        {
        //            using (WebAppDbContext db = new WebAppDbContext())
        //            {
        //                db.tbl_PartType.Add(tbl_PartType);
        //                db.SaveChanges();
        //            }
        //        }
        //        else
        //        {
        //            _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //            return PartialView("_Create");
        //        }
                
        //        _logger.Log(LogLevel.Trace, actionName + " :: ended.");

        //        Alert("Data Saved Sucessfully!!!", NotificationType.success);
        //        return RedirectToAction("Index");
        //    }
        //    catch(Exception ex)
        //    {
        //        _logger.Log(LogLevel.Error, actionName + " EXCEPTION :: " + ex.ToString() + " INNER EXCEPTION :: " + ex.InnerException?.ToString());
        //        Alert("Their is something went wrong!!!", NotificationType.error);
        //        return RedirectToAction("Index");
        //    }
        //}
 
        //public ActionResult Edit(string id)
        //{
        //    string actionName = "Create";
        //    tbl_PartType response = new tbl_PartType();
        //    try
        //    {
        //        _logger.Log(LogLevel.Trace, actionName + " :: started.");
        //        if (String.IsNullOrWhiteSpace(id))
        //        {
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }
        //        else
        //        {
        //            using (WebAppDbContext db = new WebAppDbContext())
        //            {
        //                response = db.tbl_PartType.FirstOrDefault(x => x.PartTypeID == id);
        //            }
        //        }
        //        _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //    }
        //    catch(Exception ex)
        //    {
        //        _logger.Log(LogLevel.Error, actionName + " EXCEPTION :: " + ex.ToString() + " INNER EXCEPTION :: " + ex.InnerException?.ToString());
        //    }
    
        //    return PartialView("_Edit", response);
        //}
 
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(string id, tbl_PartType tbl_PartType)
        //{
        //    string actionName = "Edit";
        //    try
        //    {
        //        _logger.Log(LogLevel.Trace, actionName + " :: started.");
        //        if (String.IsNullOrWhiteSpace(id))
        //        {
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }
        //        else
        //        {
        //            if(ModelState.IsValid)
        //            {
        //                using (WebAppDbContext db = new WebAppDbContext())
        //                {
        //                    db.Entry(tbl_PartType).State = System.Data.Entity.EntityState.Modified;
        //                    db.SaveChanges();
        //                }
        //            }
        //            else
        //            {
        //                _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //                return PartialView("_Edit");
        //            }
        //        }

        //        _logger.Log(LogLevel.Trace, actionName + " :: ended.");

        //        Alert("Record Updated Sucessfully!!!", NotificationType.success);
        //        return RedirectToAction("Index");
        //    }
        //    catch(Exception ex)
        //    {
        //        _logger.Log(LogLevel.Error, actionName + " EXCEPTION :: " + ex.ToString() + " INNER EXCEPTION :: " + ex.InnerException?.ToString());
        //        Alert("Their is something went wrong!!!", NotificationType.error);
        //        return RedirectToAction("Index");
        //    }
        //}

        //public ActionResult Delete(string id)
        //{
        //    string actionName = "Delete";
        //    tbl_PartType response = new tbl_PartType();
        //    try
        //    {
        //        _logger.Log(LogLevel.Trace, actionName + " :: started.");
        //        if (String.IsNullOrWhiteSpace(id))
        //        {
        //            _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }
        //        else
        //        {
        //            using (WebAppDbContext db = new WebAppDbContext())
        //            {
        //                response = db.tbl_PartType.FirstOrDefault(x => x.PartTypeID == id);
        //            }
        //        }
        //    }
        //    catch(Exception ex)
        //    {
        //        _logger.Log(LogLevel.Error, actionName + " EXCEPTION :: " + ex.ToString() + " INNER EXCEPTION :: " + ex.InnerException?.ToString());
        //    }
        //    _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //    return PartialView("_Delete", response);
        //}
 
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(string id, tbl_PartType tbl_PartType)
        //{
        //    string actionName = "Delete";
        //    try
        //    {
        //        _logger.Log(LogLevel.Trace, actionName + " :: started.");
        //        if (String.IsNullOrWhiteSpace(id))
        //        {
        //            _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }
        //        else
        //        {
        //            // TODO: Add delete logic here
        //            using (WebAppDbContext db = new WebAppDbContext())
        //            {
        //                var response = db.tbl_PartType.FirstOrDefault(x => x.PartTypeID == id);
        //                if (response != null)
        //                {
        //                    db.tbl_PartType.Remove(response);
        //                    db.SaveChanges();
        //                }
        //                else
        //                {
        //                    _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //                    Alert("Record not found!!!", NotificationType.error);
        //                    return RedirectToAction("Index");
        //                }
        //            }

        //            _logger.Log(LogLevel.Trace, actionName + " :: ended.");
        //            Alert("Record Deleted Sucessfully!!!", NotificationType.success);
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    catch(Exception ex)
        //    {
        //        _logger.Log(LogLevel.Error, actionName + " EXCEPTION :: " + ex.ToString() + " INNER EXCEPTION :: " + ex.InnerException?.ToString());
        //        Alert("Their is something went wrong!!!", NotificationType.error);
        //        return RedirectToAction("Index");
        //    }
        //}

    }
}

CMMS.Web/Views/PartType/Index.cshtml
@model IEnumerable<ClassLibrary.Models.tbl_PartType>
@{
    ViewBag.Title = "Index";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h4>Part Types</h4>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<section class="content">
  
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">

                <!-- jquery validation -->
                <div class="card">
                    <div class="card-header">
                        @*<a class="btn btn-success" data-modal='' href="@Url.Action("Create","PartType")"><i class="fa fa-plus"></i> Add New Type</a>*@

                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Part Id</th>
                                    <th>Part Name</th>
               
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td> @item.PartTypeID</td>
                                        <td> @item.PartName</td>

                                        @{
                                            if (this.User.IsInRole("Admin"))
                                            {
                                                <td>
                                                    <a class="btn-primary btn-sm" data-modal='' href="@Url.Action("Edit", "PartType", new { id = item.PartTypeID  })"><i class="fas fa-edit"></i></a> |
                                                    <a class="btn-info btn-sm" data-modal='' href="@Url.Action("Details", "PartType", new { id = item.PartTypeID }) "><i class="fa fa-eye"></i></a> |
                                                    <a class="btn-danger btn-sm" data-modal='' href="@Url.Action("Delete", "PartType", new { id = item.PartTypeID})"><i class="fa fa-trash"></i></a>

                                                </td> }
                                            else
                                            {
                                                <td>
                                                    <a class="btn-info btn-sm" data-modal='' href="@Url.Action("Details", "PartType", new { id = item.PartTypeID }) "><i class="fa fa-eye"></i></a> |
                                                </td> }

                                        }

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">

                    </div>

                </div>
                <!-- /.card -->

            </div>
            <!--/.col (left) -->
            <!--/.col (right) -->
        </div>
        <!-- /.row -->

</section>

<script>
    $(function () {
        $('#example1').DataTable()
    });
</script>


<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


@section scripts{
    @Scripts.Render("~/Scripts/common/modalPopup.js")
}

CMMS.Web/Views/PartType/_Create.cshtml
@model ClassLibrary.Models.tbl_PartType
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<div class="modal-header">
    <h4 class="modal-title"><b>Add MCAT Type</b></h4>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>



<div class="modal-body">
    @using (Html.BeginForm("Create", "PartType", FormMethod.Post, new {  @id = "myForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="box box-primary box-solid">
            <div class="box-header">
                <div class="form-group row">
                    <div class=" col-md-3"></div>
                </div>
            </div>
            <br />

           <!-- /.card-header -->
            <!-- form start -->
            <div class="box-body" id="InputFields">
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Part Type ID</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PartTypeID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PartTypeID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PartName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PartName, "", new { @class = "text-danger" })
                    </div>
                </div>
              
            </div>

        </div>

        <div class="modal-footer" id="footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    }

</div>

CMMS.Web/Views/PartType/_Delete.cshtml
@model ClassLibrary.Models.tbl_PartType
<style>
    .modal-dialog {
        width: 40% !important;
    }
</style>
<div class="modal-header">
    <h4 class="modal-title"> Confirm Delete</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<div class="modal-body">
        
        <h3 style="color:red">Are you sure you want to delete this?</h3>
</div>

<div class="modal-footer">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="btn btn-default" data-dismiss="modal">Close</button>
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>
    

CMMS.Web/Views/PartType/_Details.cshtml
@model ClassLibrary.Models.tbl_PartType
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

<div class="modal-header">
    <h4 class="modal-title"><b>View MCAT Type</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<div class="modal-body">
        @Html.HiddenFor(model => model.PartTypeID)
        <div class="box box-primary box-solid">
            <div class="box-header">
          
                <div class="form-group row">
                    <div class=" col-md-3"></div>
                </div>
            </div>
            <br />

            <!-- /.card-header -->
            <!-- form start -->
            <div class="box-body" id="InputFields">
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Id</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PartTypeID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                        @Html.ValidationMessageFor(model => model.PartTypeID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PartName, new { htmlAttributes = new { @class = "form-control", @disabled="disabled" } })
                        @Html.ValidationMessageFor(model => model.PartName, "", new { @class = "text-danger" })
                    </div>
                </div>                
            </div>

        </div>

        <div class="modal-footer" id="footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>


</div>

CMMS.Web/Views/PartType/_Edit.cshtml
@model ClassLibrary.Models.tbl_PartType
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

<div class="modal-header">
    <h4 class="modal-title"><b>Part Type</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<div class="modal-body">
    @using (Html.BeginForm("Edit", "PartType", FormMethod.Post, new { @id = "myForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PartTypeID)
        <div class="box box-primary box-solid">
            <div class="box-header">
                <div class="form-group row">
                    <div class=" col-md-3"></div>
                </div>
            </div>
            <br />

            <!-- /.card-header -->
            <!-- form start -->
            <div class="box-body" id="InputFields">
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Id</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PartTypeID, new { htmlAttributes = new { @class = "form-control",@readonly=true } })
                        @Html.ValidationMessageFor(model => model.PartTypeID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PartName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PartName, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

        </div>

        <div class="modal-footer" id="footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <input type="submit" value="Save Changes" class="btn btn-primary" />
        </div>
    }

</div>