CMMS.Web/Controllers/MCATController.cs
using ClassLibrary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Helpers;
using static ClassLibrary.Common.Enums;

namespace WebApplication.Controllers
{
    [CustomAuthorization]
    public class MCATController : BaseController
    {
        // GET: AwardType
 
        public ActionResult Index()
        {
            using (WebAppDbContext db = new WebAppDbContext())
            {
                var abc = db.tbl_MCAT.ToList();
                return View(abc);
            }
        }

        // GET: AreaType/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (WebAppDbContext db = new WebAppDbContext())
            {
                var abc = db.tbl_MCAT.Where(x => x.MCAT_ID == id).FirstOrDefault();
                return PartialView("_Details", abc);
            }
        }

        //GET: AreaType/Create
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        // POST: AreaType/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tbl_MCAT tbl_MCAT)
        {
            try
            {
                // TODO: Add insert logic here
                using (WebAppDbContext db = new WebAppDbContext())
                {
                    if (!ModelState.IsValid)
                    {
                        return PartialView("_Create");
                    }
                    db.tbl_MCAT.Add(tbl_MCAT);
                    db.SaveChanges();
                }
                Alert("Data Saved Sucessfully!!!", NotificationType.success);
                return RedirectToAction("Index");
            }
            catch
            {
                Alert("Their is something went wrong!!!", NotificationType.error);
                return RedirectToAction("Index");
            }
        }

        // GET: AreaType/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (WebAppDbContext db = new WebAppDbContext())
            {
                var abc = db.tbl_MCAT.Where(x => x.MCAT_ID == id).FirstOrDefault();
                return PartialView("_Edit", abc);
            }
        }

        // POST: AreaType/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, tbl_MCAT tbl_MCAT)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                // TODO: Add update logic here
                using (WebAppDbContext db = new WebAppDbContext())
                {
                    if (!ModelState.IsValid)
                    {
                        return PartialView("_Edit");
                    }
                    db.Entry(tbl_MCAT).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                Alert("Record Updated Sucessfully!!!", NotificationType.success);
                return RedirectToAction("Index");
            }
            catch
            {
                Alert("Their is something went wrong!!!", NotificationType.error);
                return RedirectToAction("Index");
            }
        }

        // GET: AreaType/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (WebAppDbContext db = new WebAppDbContext())
            {
                var abc = db.tbl_MCAT.Where(x => x.MCAT_ID == id).FirstOrDefault();
                return PartialView("_Delete", abc);
            }
        }

        // POST: AreaType/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, tbl_MCAT tbl_MCAT)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                // TODO: Add delete logic here
                using (WebAppDbContext db = new WebAppDbContext())
                {
                    var abc = db.tbl_MCAT.Where(x => x.MCAT_ID == id).FirstOrDefault();
                    db.tbl_MCAT.Remove(abc);
                    db.SaveChanges();
                }
                Alert("Record Deleted Sucessfully!!!", NotificationType.success);
                return RedirectToAction("Index");
            }
            catch
            {
                Alert("Their is something went wrong!!!", NotificationType.error);
                return RedirectToAction("Index");
            }
        }

    }
}

CMMS.Web/Views/MCAT/Index.cshtml
@model IEnumerable<ClassLibrary.Models.tbl_MCAT>
@{
    ViewBag.Title = "Index";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h4>MCAT Records</h4>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<section class="content">
  
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">

                <!-- jquery validation -->
                <div class="card">
                    <div class="card-header">
                        @*<a class="btn btn-success" data-modal='' href="@Url.Action("Create","MCAT")"><i class="fa fa-plus"></i> Add New Type</a>*@
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>               
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td> @item.MCAT_ID</td>
                                        <td> @item.MCAT_Name</td>
                                        @{
                                            if (this.User.IsInRole("Admin"))
                                            {
                                                <td>
                                                    <a class="btn-primary btn-sm" data-modal='' href="/Mcat/Edit/"><i class="fas fa-edit"></i></a> |
                                                    <a class="btn-info btn-sm" data-modal='' href="@Url.Action("Details", "MCAT", new { id = item.MCAT_ID,@disabled=true }) "><i class="fa fa-eye"></i></a> |
                                                    <a class="btn-danger btn-sm" data-modal='' href="@Url.Action("Delete", "MCAT", new { id = item.MCAT_ID ,@disabled=true})"><i class="fa fa-trash"></i></a>

                                                </td> }
                                            else
                                            {
                                                <td>
                                                    <a class="btn-info btn-sm" data-modal='' href="@Url.Action("Details", "MCAT", new { id = item.MCAT_ID,@disabled=true }) "><i class="fa fa-eye"></i></a> |
                                                </td> }

                                        }

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">

                    </div>

                </div>
                <!-- /.card -->

            </div>
            <!--/.col (left) -->
            <!--/.col (right) -->
        </div>
        <!-- /.row -->

</section>

<script>
    $(function () {
        $('#example1').DataTable()
    });
</script>


<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>


@section scripts{
    @Scripts.Render("~/Scripts/common/modalPopup.js")
}

CMMS.Web/Views/MCAT/_Create.cshtml
@model ClassLibrary.Models.tbl_MCAT
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<div class="modal-header">
    <h4 class="modal-title"><b>Add MCAT Type</b></h4>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>



<div class="modal-body">
    @using (Html.BeginForm("Create", "MCAT", FormMethod.Post, new {  @id = "myForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="box box-primary box-solid">
            <div class="box-header">
                <div class="form-group row">
                    <div class=" col-md-3"></div>
                </div>
            </div>
            <br />

           <!-- /.card-header -->
            <!-- form start -->
            <div class="box-body" id="InputFields">
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">MCAT ID</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MCAT_ID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MCAT_ID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MCAT_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MCAT_Name, "", new { @class = "text-danger" })
                    </div>
                </div>
              
            </div>

        </div>

        <div class="modal-footer" id="footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <input type="submit" value="Submit" class="btn btn-primary" />
        </div>
    }

</div>

CMMS.Web/Views/MCAT/_Delete.cshtml
@model ClassLibrary.Models.tbl_MCAT
<style>
    .modal-dialog {
        width: 40% !important;
    }
</style>
<div class="modal-header">
    <h4 class="modal-title"> Confirm Delete</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<div class="modal-body">
        
        <h3 style="color:red">Are you sure you want to delete this?</h3>
</div>

<div class="modal-footer">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="btn btn-default" data-dismiss="modal">Close</button>
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>
    

CMMS.Web/Views/MCAT/_Details.cshtml
@model ClassLibrary.Models.tbl_MCAT
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

<div class="modal-header">
    <h4 class="modal-title"><b>View MCAT Type</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<div class="modal-body">
        @Html.HiddenFor(model => model.MCAT_ID)
        <div class="box box-primary box-solid">
            <div class="box-header">
          
                <div class="form-group row">
                    <div class=" col-md-3"></div>
                </div>
            </div>
            <br />

            <!-- /.card-header -->
            <!-- form start -->
            <div class="box-body" id="InputFields">
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Id</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MCAT_ID, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                        @Html.ValidationMessageFor(model => model.MCAT_ID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MCAT_Name, new { htmlAttributes = new { @class = "form-control", @disabled="disabled" } })
                        @Html.ValidationMessageFor(model => model.MCAT_Name, "", new { @class = "text-danger" })
                    </div>
                </div>                
            </div>

        </div>

        <div class="modal-footer" id="footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>


</div>

CMMS.Web/Views/MCAT/_Edit.cshtml
@model ClassLibrary.Models.tbl_MCAT
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

<div class="modal-header">
    <h4 class="modal-title"><b>MCAT Type</b></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


<div class="modal-body">
    @using (Html.BeginForm("Edit", "MCAT", FormMethod.Post, new { @id = "myForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MCAT_ID)
        <div class="box box-primary box-solid">
            <div class="box-header">
                <div class="form-group row">
                    <div class=" col-md-3"></div>
                </div>
            </div>
            <br />

            <!-- /.card-header -->
            <!-- form start -->
            <div class="box-body" id="InputFields">
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Id</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MCAT_ID, new { htmlAttributes = new { @class = "form-control",@readonly=true } })
                        @Html.ValidationMessageFor(model => model.MCAT_ID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 col-form-label">Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MCAT_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MCAT_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

        </div>

        <div class="modal-footer" id="footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <input type="submit" value="Save Changes" class="btn btn-primary" />
        </div>
    }

</div>