CMMS.Web/Controllers/CustomDashBoardController.cs
using ClassLibrary.Models;
using ClassLibrary.ViewModels;
using CMMS.Web.Helper;
using ILS.UserManagement.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class CustomDashboardController : Controller
    {
        private const string AllRoles = "AllRoles";
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ClientMode()
        {
            return View("ClientMode");
        }

        public ActionResult DesignerMode()
        {
            return View("DesignerMode");
        }

        public ActionResult UserDashboards()
        {
            return View("UserDashboards");
        }

        public ActionResult LoadUsers(int length, int start)
        {
            int recordCount = 0, filterrecord = 0;
            dynamic userDashboardMappingData = null;

            try
            {
                using (var db = new Entities())
                {
                    string searchvalue = Request.Form["search[value]"];
                    var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                    var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                    Expression<Func<tbl_User, object>> sortExpression;
                    switch (sortColumn)
                    {
                        case "UserId":
                            sortExpression = (x => x.UserId);
                            break;
                        case "UserName":
                            sortExpression = (x => x.Name);
                            break;
                        default:
                            sortExpression = (x => x.UserId);
                            break;
                    }

                    if (sortColumnDir == "asc")
                    {
                        userDashboardMappingData = db.tbl_User.Where(x => x.UserId.Contains(searchvalue)
                     || x.Name.Contains(searchvalue))
                     .OrderBy(sortExpression).Skip(start).Take(length).Where(x => x.IsActive != 0).ToList().Select(y => new { UserId = y.UserId, UserName = y.Name });
                    }
                    else
                    {
                        userDashboardMappingData = db.tbl_User.Where(x => x.UserId.Contains(searchvalue)
                    || x.Name.Contains(searchvalue))
                    .OrderByDescending(sortExpression).Skip(start).Take(length).Where(x => x.IsActive != 0).ToList().Select(y => new { UserId = y.UserId, UserName = y.Name });
                    }

                    var recordcount = db.tbl_User.Count();

                    if (searchvalue != "")
                    {
                        filterrecord = userDashboardMappingData.Count();
                    }
                    else
                    {
                        filterrecord = recordcount;
                    }
                }
            }
            catch
            {

            }

            var response = new { recordsTotal = recordCount, recordsFiltered = filterrecord, data = userDashboardMappingData };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult LinkedDashboards(string userId)
        {
            TempData["UserId"] = userId;
            ViewBag.UserId = userId;
            return View("UserDashboards");
        }

        [HttpPost]
        public ActionResult LoadUserDashboard(int length, int start)
        {
            string userId = TempData["UserId"]?.ToString();
            int recordCount = 0, filterrecord = 0;
            List<UserDashboardMapping> userDashboardMappingData = new List<UserDashboardMapping>();

            try
            {
                using (WebAppDbContext db = new WebAppDbContext())
                {
                    string searchvalue = Request.Form["search[value]"];
                    var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                    var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                    Expression<Func<UserDashboardMapping, object>> sortExpression;
                    switch (sortColumn)
                    {
                        case "UserId":
                            sortExpression = (x => x.UserId);
                            break;
                        default:
                            sortExpression = (x => x.UserId);
                            break;
                    }

                    if (sortColumnDir == "asc")
                    {
                        userDashboardMappingData = db.UserDashboardMappings.Where(x => x.UserId.Contains(userId))
                       .OrderBy(sortExpression).Skip(start).Take(length).ToList();
                    }
                    else
                    {
                        userDashboardMappingData = db.UserDashboardMappings.Where(x => x.UserId.Contains(userId))
                        .OrderByDescending(sortExpression).Skip(start).Take(length).ToList();
                    }

                    var recordcount = db.UserDashboardMappings.Where(x => x.UserId == userId).Count();

                    if (searchvalue != "")
                    {
                        filterrecord = userDashboardMappingData.Count();
                    }
                    else
                    {
                        filterrecord = recordcount;
                    }
                }
            }
            catch (Exception ex)
            {

            }

            var response = new { recordsTotal = recordCount, recordsFiltered = filterrecord, data = userDashboardMappingData };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddUserDashboard(string userId)
        {
            ViewBag.PageMode = PageMode.Add;
            return RedirectToAction("PopulateUserData", new { userId = userId, roleId = "", dashboardId = "", pageMode = PageMode.Add });
        }

        [HttpPost]
        public ActionResult EditUserDashboard(string userId,string dashboardId,string roleId)
        {
            ViewBag.PageMode = PageMode.Edit;
            return RedirectToAction("PopulateUserData", new { userId = userId,roleId = roleId, dashboardId = dashboardId, pageMode = PageMode.Edit });
        }

        [HttpPost]
        public ActionResult DeleteDashboard(string DashboardID)
        {
            var dashboardPath = $"~/{ConfigurationManager.AppSettings["DashboardPath"]?.ToString()}";
            CustomDashboardStorage newDashboardStorage = new CustomDashboardStorage(dashboardPath);

            newDashboardStorage.DeleteDashboard(HttpContext.Request.MapPath(Path.Combine(dashboardPath, $"{DashboardID}.xml")));
            return new EmptyResult();
        }

        [HttpPost]
        public ActionResult GetRoles(string id)
        {
            if (!string.IsNullOrWhiteSpace(id))
            {
                using (var context = new Entities())
                {
                    var userRoles = context.tbl_UserRole.Where(y => y.UserId == id && y.IsDeleted != 1).Select(z => z.RoleId);
                    var response = context.tbl_Role.Where(x => userRoles.Contains(x.RoleId) && x.IsDeleted != 1).Select(x => new
                    {
                        RoleId = x.RoleId,
                        RoleName = x.Name
                    }).ToList();

                    return Json(response, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetAvailableDashboards(string userId, string roleId)
        {
            if (!string.IsNullOrWhiteSpace(userId) && !string.IsNullOrWhiteSpace(roleId))
            {
                using (var context = new WebAppDbContext())
                {
                    var response = GetDashboards(userId, roleId);
                    return Json(response, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Save(string userId, string roleId, string dashboardId,string isDefault, string pageMode)
        {
            var type = "success";
            var msg = pageMode == PageMode.Add.ToString() ? "Plan added successfully." : "Plan updated successfully.";

            isDefault = String.IsNullOrWhiteSpace(isDefault) ? "0" : isDefault;
            try
            {
                if (!string.IsNullOrWhiteSpace(userId) && !string.IsNullOrWhiteSpace(roleId) && !string.IsNullOrWhiteSpace(dashboardId))
                {
                    using (var context = new WebAppDbContext())
                    {

                        if (roleId == AllRoles)
                        {
                            context.UserDashboardMappings.RemoveRange(context.UserDashboardMappings.Where(x => x.UserId == userId));

                            var roles = GetUserRoles(userId);
                            List<UserDashboardMapping> models = new List<UserDashboardMapping>();
                            foreach (var role in roles)
                            {
                                UserDashboardMapping model = new UserDashboardMapping()
                                {
                                    UserId = userId,
                                    RoleId = role.RoleId,

CMMS.Web/Views/CustomDashBoard/ClientMode.cshtml
@model ClassLibrary.Models.UserDashboardMapping
@using System.Web.UI.WebControls;
@{ 
    bool disableServerControl = false;

    if(Model.IsDefault == "1")
    {
        disableServerControl = true;
    }
}

<style>
    .dx-dashboard-widget-container {
        min-height: 100vh !important;
    }
</style>

<script src="~/Scripts/CustomDashboard/DeleteExtension.js"></script>
<script src="~/Scripts/CustomDashboard/SaveAsExtension.js"></script>


<script type="text/html" id="dx-save-as-form">
    <div>Dashboard Name:</div>
    <div style="margin: 10px 0" data-bind="dxTextBox: { value: newName }"></div>
    <div data-bind="dxButton: { text: 'Save', onClick: saveAs  }"></div>

</script>

<div id="dashWrapper">

    <div id="#Dashboard" style="height:100%;">

        @Html.DevExpress().Button(settings =>
        {
            settings.Name = "SwitchWorkingModesButton";
            settings.Text = "Switch to Designer";
            settings.UseSubmitBehavior = true;
            settings.ClientSideEvents.Click = "function(s, e) { switchWorkingModes(s, e); }";
        }).GetHtml()



        @Html.DevExpress().Dashboard(settings =>
        {
            settings.Name = "Dashboard";
            settings.Width = Unit.Percentage(100);
            settings.Height = Unit.Percentage(100);
            settings.EnableSqlDataSource = true;
            settings.ClientSideEvents.BeforeRender = "function(s, e) { customizeMenu(s, e); }";
            settings.WorkingMode = DevExpress.DashboardWeb.WorkingMode.Viewer;
            settings.InitialDashboardId = Model.DashboardId;

        }).GetHtml()
    </div>
    </div>
    <script>

    function switchWorkingModes(s, e) {
        var workingMode = Dashboard.GetWorkingMode();
        if (workingMode == 'designer') {
            Dashboard.SwitchToViewer();
            SwitchWorkingModesButton.SetText('Switch to Designer');
        }
        else {
            Dashboard.SwitchToDesigner();
            SwitchWorkingModesButton.SetText('Switch to Viewer');
        }
    }


    function customizeMenu(s, e) {

        var control = s.GetDashboardControl();

        if (!@Html.Encode(disableServerControl).ToLower()) {
            control.registerExtension(new DeleteDashboardExtension(s));
        }
        control.registerExtension(new SaveAsDashboardExtension(control, '@Model.UserId', '@Model.RoleId'));

        control.unregisterExtension("create-dashboard");
        control.unregisterExtension("available-data-sources");
        control.unregisterExtension("data-source-wizard");
        control.unregisterExtension("open-dashboard");
    }


    </script>

CMMS.Web/Views/CustomDashBoard/DesignerMode.cshtml
@using System.Web.UI.WebControls;

<style>
    .dx-dashboard-widget-container{
        min-height:100vh !important;
    }
</style>
<script src="~/Scripts/CustomDashboard/DeleteExtension.js"></script>
<script src="~/Scripts/CustomDashboard/SaveAsExtension.js"></script>

<div id="dashWrapper">

    <div id="#Dashboard" style="height:100%;">
        @Html.DevExpress().Button(settings =>
        {
           settings.Name = "SwitchWorkingModesButton";
           settings.Text = "Switch to Viewer";
           settings.UseSubmitBehavior = true;
           settings.ClientSideEvents.Click = "function(s, e) { switchWorkingModes(s, e); }";
        }).GetHtml()


        @Html.DevExpress().Dashboard(settings =>
    {
        settings.Name = "Dashboard";
        settings.Width = Unit.Percentage(100);
        settings.Height = Unit.Percentage(100);
        settings.EnableSqlDataSource = true;
        settings.ClientSideEvents.BeforeRender = "function(s, e) { customizeMenu(s, e); }";
        settings.WorkingMode = DevExpress.DashboardWeb.WorkingMode.Designer;
        settings.MobileLayoutEnabled = DevExpress.DashboardWeb.MobileLayoutMode.Auto;


    }).GetHtml()
    </div>
</div>
<script>

    function switchWorkingModes(s, e) {
        var workingMode = Dashboard.GetWorkingMode();
        if (workingMode == 'designer') {
            Dashboard.SwitchToViewer();
            SwitchWorkingModesButton.SetText('Switch to Designer');
        }
        else {
            Dashboard.SwitchToDesigner();
            SwitchWorkingModesButton.SetText('Switch to Viewer');
        }
    }

    function customizeMenu(s, e) {
        var control = s.GetDashboardControl();
        control.registerExtension(new SaveAsDashboardExtension(control));
        control.registerExtension(new DeleteDashboardExtension(s))
    }


</script>

CMMS.Web/Views/CustomDashBoard/Index.cshtml
@using CMMS.Web.Helper
@{
    Layout = "~/Views/Shared/_LayoutPageNew.cshtml";
}

<style>
    .hide {
        display: none;
    }
</style>

<link href="~/Content/sweetalert.css" rel="stylesheet" />
<script src="~/Scripts/sweetalert.min.js"></script>

<script>
    var permissions;

    var dtFormat = 'DD/MM/YYYY';

    $(document).ready(function ()
    {

        var table;
        table = $('#tblUserDashboards').DataTable(
            {
                "bServerSide": true,
                "processing": true,
                "scrollX": true,
                "paging": true,
                "filter": true,
                "order": [[1, 'asc']],
                "lengthMenu": [[10, 25, 50,100,-1], [10, 25,50,100, "All"]],

                ajax: {
                    type: 'POST',
                    url: '@Url.Action("LoadUsers")',
                    dataType: 'json',
                    dataSrc: 'data',
                },

                columns: [

                    { 'data': 'UserId', "name": "User Id"},
                    { 'data': 'UserName', "name": "Role Id" },
                     {
                        'data': function (data, type, row, meta) {
                            var actions = '';

                           // if (permissions.filter(obj => obj.PermissionId == "EditUserDashboardMapping").length > 0) {
                             actions = '<a id="btnEditMapping" class="btn btn-primary btn-xs select"   href="/CustomDashboard/LinkedDashboards?userId=' + data.UserId + '"><i class="fa fa-pencil"></i >' + 'Edit' + '</a>';
                           // }
                            //else {
                            //    actions = '<a id="btnEditMapping" class="btn btn-primary btn-xs select disabled"   href="/CustomDashboard/LinkedDashboards/' + data.UserId + '"><i class="fa fa-pencil"></i >' + 'Edit' + '</a>';
                            //}

                            actions = actions + " " + '|' + " ";

                           // if (permissions.filter(obj => obj.PermissionId == "DeleteUserDashboardMapping").length > 0) {
                                actions = actions + '<a id="btnDelMapping" class="btn btn-danger btn-xs select"  href="/CustomDashboard/Delete/' + data.UserId + '">' + 'Delete' + '</a>';
                         ////   }
                            //else {
                            //    actions = actions + '<a id="btnDelMapping" class="btn btn-danger btn-xs select disabled" href="/CustomDashboard/Delete/' + data.UserId + '">' + 'Delete' + '</a>';
                            //}

                            return actions;
                        }
                    },
                ],


               "rowCallback": function (row, data, dataIndex) {
                   //if (data["Status"] == "InActive") {
                   //    $('td', row).css('background-color', 'red');

                   //}
               },

            });

        $('#tblUserDashboards tbody').on("click", '.select', function () {
            var tblData = table.rows($(this).closest('tr')).data();

            window.location.href = '@Url.Action("LinkedDashboards", "CustomDashboard")' + '?userId=' + tblData[0].UserId;

            return false;
        });
    });

</script>


<section class="content">
    <div class="container-fluid">
        <div class="row">
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-header">
                        <h4 class="card-title" style="font-weight:bold">Users</h4>
                    </div>

                    <div class="card-body">
                        <table id="tblUserDashboards" class="table table-bordered table-striped"  style="width:100%" >
                            <thead>
                                <tr>
                                    <th>User Id</th>
                                    <th>User Name</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                            </tbody>

                        </table>
                    </div>

                    <div class="card-footer">
                    </div>

                </div>
            </div>
        </div>
    </div>

</section>

@section scripts{
    @Scripts.Render("~/Scripts/Common/ModalPopup.js")
}

CMMS.Web/Views/CustomDashBoard/UserDashboards.cshtml
@using CMMS.Web.Helper
@{
    Layout = "~/Views/Shared/_LayoutPageNew.cshtml";
    var userId = ViewBag.UserId;
}

<style>
    .hide {
        display: none;
    }
</style>

<link href="~/Content/sweetalert.css" rel="stylesheet" />
<script src="~/Scripts/sweetalert.min.js"></script>

<script>
    var permissions;

    var dtFormat = 'DD/MM/YYYY';

    $(document).ready(function ()
    {
        permissions = @Html.Raw(Json.Encode(((SessionHelper)Session[SessionKeys.SessionHelperInstance]).CurrentRolePermissions));

        if (!permissions.filter(obj => obj.PermissionId == "AssignDashboard").length > 0)
        {
            $("#btnAssignDashboard").attr('disabled', 'disabled')
        }

        var table;
        table = $('#tblUserDashboards').DataTable(
            {
                "bServerSide": true,
                "processing": true,
                "scrollX": true,
                "paging": true,
                "filter": true,
                "order": [[1, 'asc']],
                "lengthMenu": [[10, 25, 50,100,-1], [10, 25,50,100, "All"]],

                ajax: {
                    type: 'POST',
                    url: '@Url.Action("LoadUserDashboard")',
                    dataType: 'json',

                    dataSrc: 'data',
                },

                columns: [
                    { 'data': 'Id', "name": "Id",  },
                    { 'data': 'UserId', "name": "User Id", },
                    { 'data': 'RoleId', "name": "Role Id", },
                    { 'data': 'DashboardId', "name": "Dashboard Id", },
                    { 'data': 'InsertedBy', "name": "Inserted By", },
                    {
                        'data': 'InsertionDateTime',
                        "name": "Insertion Date Time",
                        "render": function (value) {
                            if (value === null) return "N/A";
                            return moment(value).format(dtFormat);
                        }
                    },
                    { 'data': 'LastUpdatedBy', "name": "LastUpdatedBy", },
                      {
                        'data': 'LastUpdatedDateTime',
                        "name": "Last Updated Date Time",
                        "render": function (value) {
                            if (value === null) return "N/A";
                            return moment(value).format(dtFormat);
                        }
                    },
                    { 'data': 'IsDefault', "name": "Default" },
                    { 'data': 'IsPrefered', "name": "Prefered" },
                     {
                        'data': function (data, type, row, meta) {
                            var actions = '';

                            if (permissions.filter(obj => obj.PermissionId == "EditUserDashboardMapping").length > 0) {
                                actions = '<a id="btnEditMapping" class="btn btn-primary btn-xs select"><i class="fa fa-pencil"></i >' + 'Edit' + '</a>';
                            }
                            else {
                                actions = '<a id="btnEditMapping" class="btn btn-primary btn-xs select disabled"><i class="fa fa-pencil"></i >' + 'Edit' + '</a>';
                            }

                            actions = actions + " " + '|' + " ";

                            if (permissions.filter(obj => obj.PermissionId == "DeleteUserDashboardMapping").length > 0) {
                                actions = actions + '<a id="btnDelMapping" class="btn btn-danger btn-xs select" >' + 'Delete' + '</a>';
                            }
                            else {
                                actions = actions + '<a id="btnDelMapping" class="btn btn-danger btn-xs select disabled" >' + 'Delete' + '</a>';
                            }

                            return actions;
                        }
                    },
                ],

                "columnDefs": [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }],
               "rowCallback": function (row, data, dataIndex) {
                   if (data["Status"] == "InActive") {
                       $('td', row).css('background-color', 'red');

                   }
               },

            });


        $('#tblUserDashboards tbody').on("click", '#btnEditMapping', function () {
            var tblData = table.rows($(this).closest('tr')).data();

            var options = {
                "backdrop": "static",
                keyboard: true
            };

          $.ajax({
                type: "POST",
                url: '@Url.Action("EditUserDashboard", "CustomDashboard")',
              contentType: "application/json; charset=utf-8",
               data: JSON.stringify({ userId: '@userId', dashboardId: tblData[0].DashboardId, roleId: tblData[0].RoleId }),
                datatype: "json",
                success: function(data)
                {
                    $('#myModalContent').html(data);
                    $('#addEditMappingModal').modal(options);
                    $('#addEditMappingModal').modal('show');
               },
               failure: function () {
               },
               error: function (data,abc,xyz) {

                    alert("Content load failed.");
                }
            });

            return false;
        });


        $('#tblUserDashboards tbody').on("click", '#btnDelMapping', function () {
            var tblData = table.rows($(this).closest('tr')).data();

            var options = {
                "backdrop": "static",
                keyboard: true
            };

          $.ajax({
                type: "POST",
                url: '@Url.Action("DeleteUserDashboard", "CustomDashboard")',
              contentType: "application/json; charset=utf-8",
              data: JSON.stringify({ userId: '@userId', dashboardId: tblData[0].DashboardId, roleId: tblData[0].RoleId }),
                datatype: "json",
                success: function(data)
                {
                    if (data.type == "success") {
                        swal({ title: "Success", text: data.msg, type: "success", });


                        $('#tblUserDashboards').DataTable().ajax.reload();


                    } else {
                        swal({ title: "Error", text: data.msg, type: "error", });
                    }
               },
               failure: function () {
               },
               error: function (data,abc,xyz) {

                    alert("Content load failed.");
                }
            });''

            return false;
        });


         $("#btnAssignDashboard").click(function () {

            var options = {
                "backdrop": "static",
                keyboard: true
            };

           $.ajax({
                type: "POST",
                url: '@Url.Action("AddUserDashboard", "CustomDashboard")',
               contentType: "application/json; charset=utf-8",
               data: JSON.stringify({ userId: '@userId' }),
                datatype: "json",
                success: function(data)
                {
                    $('#myModalContent').html(data);
                    $('#addEditMappingModal').modal(options);
                    $('#addEditMappingModal').modal('show');
               },
               failure: function () {
               },
               error: function (data,abc,xyz) {

                    alert("Content load failed.");
                }
            });
        });
    });



</script>
 
<section class="content">

 
    <div class="container-fluid">

 
            <div class="row">
                <div class="col-md-12">
                    <div class="card">

                        <div class="card-header">

                            <h4 class="card-title" style="font-weight:bold">User Dashboards</h4>
                            <div class="card-tools">

                                <input type="button" value="Assign Dashboard" style="float:right;" class="btn btn-success" id="btnAssignDashboard">
                            </div>

                        </div>

                        <div class="card-body">

                            <table id="tblUserDashboards" class="table table-bordered table-striped" style="width:100%">

                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>User Id</th>
                                        <th>Role Id</th>
                                        <th>Dashboard Name</th>
                                        <th>Inserted By</th>
                                        <th>Insertion Datetime</th>
                                        <th>Last Updated By</th>
                                        <th>Last Updated Datetime</th>
                                        <th>Default</th>
                                        <th>Prefered</th>
                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>
                                </tbody>

                            </table>
                        </div>

                        <div class="card-footer">
                        </div>

                    </div>
                </div>
            </div>
        </div>

</section>


<div id='addEditMappingModal' class='modal fade'>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id='myModalContent'>

            </div>
        </div>
    </div>
</div>


@section scripts{
    @Scripts.Render("~/Scripts/Common/ModalPopup.js")
}